"""A11 REAL TLS between independent CI processes, no live endpoints.

Certificates are newly generated by OpenSSL in a disposable temp directory;
never included in the repository, release image or build artifacts.
"""
from __future__ import annotations

import asyncio
import hashlib
import json
import os
import secrets
import ssl
import subprocess
import sys
import time
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path

import pytest

from naseri_markets.a11_mtls import (
    LoopbackMtlsExchange, TransportRefused, make_client_context,
)
from naseri_markets.contracts import (
    EngineDescriptor, Instrument, Market,
)
from naseri_markets.external_abi import ExternalPaperEngine
from naseri_markets.paper_journal import PaperJournal
from naseri_markets.plugin_manager import PluginManager
from naseri_markets.plugin_runtime import ManagedPaperPlatform
from naseri_markets.private_connector import ConnectorKeys, PrivatePaperConnector
from naseri_markets.private_protocol import ReplayFence, sign_packet
from naseri_markets.quotes import QuoteOrigin, QuoteTick
from naseri_markets.registry import EngineRegistry
from naseri_markets.runtime import EngineBinding, MultiEngineRunner
from naseri_markets.sessions import SessionPolicy, TradingWindow

ROOT = Path(__file__).resolve().parents[2]
OWNER_DNS = "private-owner.fixture"
INSTRUMENT = Instrument(Market.INDEX, "fixture:quotes", "US30", "UTC", "USD")


def _openssl(*args):
    result = subprocess.run(
        ["openssl", *map(str, args)],
        check=False, capture_output=True, text=True, timeout=20,
    )
    if result.returncode:
        raise AssertionError("A11_EPHEMERAL_CERT_GENERATION_FAILED")


def _ca(directory, name):
    key, cert = directory / f"{name}.key", directory / f"{name}.crt"
    _openssl(
        "req", "-x509", "-newkey", "rsa:2048", "-nodes",
        "-days", "2", "-keyout", key, "-out", cert,
        "-subj", f"/CN={name}.fixture-ca",
        "-addext", "basicConstraints=critical,CA:TRUE",
        "-addext", "keyUsage=critical,keyCertSign,cRLSign",
    )
    return cert, key


def _identity(directory, name, dns, ca, ca_key, *, role):
    key, csr, cert = (
        directory / f"{name}.key", directory / f"{name}.csr",
        directory / f"{name}.crt",
    )
    _openssl(
        "req", "-newkey", "rsa:2048", "-nodes", "-keyout", key,
        "-out", csr, "-subj", f"/CN={dns}",
    )
    extensions = directory / f"{name}.ext"
    extensions.write_text(
        f"subjectAltName=DNS:{dns}\nextendedKeyUsage={role}\n"
        "keyUsage=digitalSignature,keyEncipherment\n",
    )
    _openssl(
        "x509", "-req", "-in", csr, "-CA", ca, "-CAkey", ca_key,
        "-CAcreateserial", "-out", cert, "-days", "2",
        "-extfile", extensions,
    )
    return cert, key


@pytest.fixture(scope="module")
def material(tmp_path_factory):
    root = tmp_path_factory.mktemp("a11-ephemeral-tls")
    ca, ca_key = _ca(root, "trusted")
    bad_ca, _ = _ca(root, "untrusted")
    server, server_key = _identity(
        root, "owner", OWNER_DNS, ca, ca_key, role="serverAuth",
    )
    client, client_key = _identity(
        root, "bot", "public-bot.fixture", ca, ca_key, role="clientAuth",
    )
    wrong_client, wrong_client_key = _identity(
        root, "wrong-client", "other-client.fixture", ca, ca_key,
        role="clientAuth",
    )
    client_hmac = root / "client-hmac.bin"
    owner_hmac = root / "owner-hmac.bin"
    for target in (client_hmac, owner_hmac):
        target.write_bytes(secrets.token_bytes(32))
        target.chmod(0o600)
    return {
        "ca": ca, "bad_ca": bad_ca,
        "server": server, "server_key": server_key,
        "client": client, "client_key": client_key,
        "wrong_client": wrong_client, "wrong_client_key": wrong_client_key,
        "client_hmac": client_hmac, "owner_hmac": owner_hmac,
    }


@asynccontextmanager
async def owner_process(material, tmp_path):
    env = dict(os.environ)
    env["GITHUB_ACTIONS"] = "true"
    env["RUNNER_ENVIRONMENT"] = "github-hosted"
    env["PYTHONPATH"] = str(ROOT)
    server = await asyncio.create_subprocess_exec(
        sys.executable, str(ROOT / "tests/fixtures/a11_owner_process.py"),
        "--ca", str(material["ca"]),
        "--cert", str(material["server"]),
        "--key", str(material["server_key"]),
        "--client-hmac", str(material["client_hmac"]),
        "--owner-hmac", str(material["owner_hmac"]),
        "--replay-db", str(tmp_path / "owner-replay.db"),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.DEVNULL,
        env=env, cwd=ROOT,
    )
    try:
        ready = await asyncio.wait_for(server.stdout.readline(), timeout=8)
        assert ready.startswith(b"A11_FIXTURE_READY:"), (
            "A11_OWNER_FIXTURE_DID_NOT_START"
        )
        port = int(ready.strip().split(b":")[-1])
        yield server, port
    finally:
        if server.returncode is None:
            server.terminate()
        try:
            await asyncio.wait_for(server.wait(), timeout=3)
        except asyncio.TimeoutError:
            server.kill()
            await server.wait()


def client_transport(material, port, *, ca=None, cert=None, key=None,
                     hostname=OWNER_DNS, timeout=2, failure_limit=2,
                     cooldown=0.15):
    context = make_client_context(
        ca=ca or material["ca"], cert=cert or material["client"],
        key=key or material["client_key"],
    )
    return LoopbackMtlsExchange(
        port=port, expected_owner_dns=hostname, context=context,
        timeout=timeout, failure_limit=failure_limit, cooldown=cooldown,
    )


def enabled_private(tmp_path):
    manager = PluginManager(tmp_path / "settings.db")
    raw = json.dumps({
        "schema_version": 1, "engine_id": "private_example",
        "engine_version": "1.0.0", "publisher": "fixture.owner",
        "visibility": "private", "adapter": "external_contract",
        "abi_version": 1, "markets": ["index"],
        "permissions": ["paper_analysis"],
    }, sort_keys=True).encode()
    digest = hashlib.sha256(raw).hexdigest()
    state = manager.register(raw, approved_sha256=digest)
    manager.set_enabled("private_example", enabled=True,
                        expected_revision=state.revision)
    return manager, digest


def setup_connector(material, tmp_path, exchange):
    manager, digest = enabled_private(tmp_path)
    fence = ReplayFence(tmp_path / "client-replay.db")
    keys = ConnectorKeys(
        "client_k1", material["client_hmac"].read_bytes(),
        "owner_k1", material["owner_hmac"].read_bytes(),
    )
    connector = PrivatePaperConnector(
        manager=manager, fence=fence, engine_id="private_example",
        engine_version="1.0.0", approved_digest=digest,
        keys=keys, exchange=exchange, timeout_seconds=3,
    )
    return manager, fence, connector


def sample_tick():
    return QuoteTick(
        INSTRUMENT, datetime.now(timezone.utc),
        Decimal("43000"), Decimal("43001"), QuoteOrigin.SYNTHETIC,
    )


def request_packet(material, *, nonce):
    now = int(time.time())
    t = sample_tick()
    body = {
        "version": 1, "key_id": "client_k1",
        "direction": "to_owner",
        "engine_id": "private_example", "engine_version": "1.0.0",
        "nonce": nonce, "request_nonce": "", "issued_at": now,
        "expires_at": now + 20,
        "payload": {
            "operation": "paper_analysis",
            "tick": {
                "market": "index", "provider": "fixture:quotes",
                "symbol": "US30", "timezone": "UTC", "quote_currency": "USD",
                "bid": "43000", "ask": "43001",
                "origin": "synthetic",
                "occurred_at": t.occurred_at.isoformat(),
            },
        },
    }
    return sign_packet(body, key=material["client_hmac"].read_bytes())


@pytest.mark.asyncio
async def test_separate_process_mtls_private_paper_e2e(tmp_path, material):
    async with owner_process(material, tmp_path) as (server, port):
        exchange = client_transport(material, port)
        manager, fence, connector = setup_connector(
            material, tmp_path, exchange,
        )
        registry = EngineRegistry()
        runner = MultiEngineRunner(registry, active=True)
        journal = PaperJournal(tmp_path / "paper.db")
        platform = ManagedPaperPlatform(
            manager, registry, runner, journal, enabled=True,
        )
        plugin = ExternalPaperEngine("private_example", "1.0.0", connector)
        tick = sample_tick()
        policy = SessionPolicy(
            "UTC", (
                TradingWindow(
                    tick.occurred_at.weekday(),
                    __import__("datetime").time(0, 0),
                    __import__("datetime").time(23, 59),
                ),
            ), verified=True,
        )
        binding = EngineBinding(
            EngineDescriptor("private_example", "1.0.0",
                             frozenset({Market.INDEX})),
            frozenset({INSTRUMENT}), policy, enabled=True,
        )
        platform.attach(binding, plugin)
        result = await platform.process(tick, now=tick.occurred_at)
        assert result.stored == 1 and result.status == "RECORDED"
        assert journal.count() == 1
        assert exchange.health.state == "READY_FOR_OFFLINE_TEST"
        assert not exchange.health.live_engine_authorized
        assert not connector.status.real_owner_authenticated
        assert not connector.status.license_authority_verified
        assert server.returncode is None
        journal.close()
        fence.close()
        manager.close()


@pytest.mark.asyncio
async def test_owner_rejects_no_client_certificate(tmp_path, material):
    async with owner_process(material, tmp_path) as (_, port):
        context = ssl.create_default_context(
            ssl.Purpose.SERVER_AUTH, cafile=str(material["ca"]),
        )
        transport = LoopbackMtlsExchange(
            port=port, expected_owner_dns=OWNER_DNS, context=context,
        )
        with pytest.raises(TransportRefused):
            await transport(request_packet(material, nonce="a" * 32))


@pytest.mark.asyncio
async def test_owner_rejects_wrong_client_identity(tmp_path, material):
    async with owner_process(material, tmp_path) as (_, port):
        transport = client_transport(
            material, port, cert=material["wrong_client"],
            key=material["wrong_client_key"],
        )
        with pytest.raises(TransportRefused):
            await transport(request_packet(material, nonce="b" * 32))


@pytest.mark.asyncio
async def test_client_rejects_wrong_server_hostname(tmp_path, material):
    async with owner_process(material, tmp_path) as (_, port):
        transport = client_transport(
            material, port, hostname="not-the-owner.fixture",
        )
        with pytest.raises(TransportRefused):
            await transport(request_packet(material, nonce="c" * 32))


@pytest.mark.asyncio
async def test_client_rejects_untrusted_ca(tmp_path, material):
    async with owner_process(material, tmp_path) as (_, port):
        transport = client_transport(
            material, port, ca=material["bad_ca"],
        )
        with pytest.raises(TransportRefused):
            await transport(request_packet(material, nonce="d" * 32))


@pytest.mark.asyncio
async def test_request_replay_is_refused_in_owner_process(tmp_path, material):
    async with owner_process(material, tmp_path) as (_, port):
        transport = client_transport(material, port)
        packet = request_packet(material, nonce="e" * 32)
        first = await transport(packet)
        assert first
        with pytest.raises(TransportRefused):
            await transport(packet)


@pytest.mark.asyncio
async def test_revoked_client_key_disables_connector(tmp_path, material):
    async with owner_process(material, tmp_path) as (_, port):
        transport = client_transport(material, port)
        manager, fence, connector = setup_connector(
            material, tmp_path, transport,
        )
        fence.revoke("owner_k1")
        with pytest.raises(ValueError, match="A10_REVOKED"):
            await connector.produce(sample_tick())
        fence.close()
        manager.close()


@pytest.mark.asyncio
async def test_server_shutdown_triggers_circuit_without_retry(tmp_path, material):
    async with owner_process(material, tmp_path) as (server, port):
        transport = client_transport(
            material, port, failure_limit=2, cooldown=0.15,
            timeout=0.5,
        )
        packet = request_packet(material, nonce="f" * 32)
        assert await transport(packet)
        server.terminate()
        await asyncio.wait_for(server.wait(), timeout=3)
        for _ in range(2):
            with pytest.raises(TransportRefused, match="EXCHANGE_UNAVAILABLE"):
                await transport(packet)
        assert transport.health.state == "OPEN"
        with pytest.raises(TransportRefused, match="CIRCUIT_OPEN"):
            await transport(packet)
        await asyncio.sleep(0.18)
        assert transport.health.state == "DEGRADED"


@pytest.mark.asyncio
async def test_live_tick_never_reaches_real_tls_transport(tmp_path, material):
    async with owner_process(material, tmp_path) as (_, port):
        exchange = client_transport(material, port)
        manager, fence, connector = setup_connector(
            material, tmp_path, exchange,
        )
        live = QuoteTick(
            INSTRUMENT, datetime.now(timezone.utc),
            Decimal("43000"), Decimal("43001"), QuoteOrigin.LIVE,
        )
        with pytest.raises(ValueError, match="LIVE_DATA_FORBIDDEN"):
            await connector.produce(live)
        assert exchange.health.consecutive_failures == 0
        fence.close()
        manager.close()


def test_insecure_transport_context_and_remote_host_disallowed(material):
    import ssl
    bare = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    bare.check_hostname = False
    bare.verify_mode = ssl.CERT_NONE
    with pytest.raises(TransportRefused):
        LoopbackMtlsExchange(
            port=1234, expected_owner_dns=OWNER_DNS, context=bare,
        )
    secure = make_client_context(
        ca=material["ca"], cert=material["client"],
        key=material["client_key"],
    )
    with pytest.raises(TransportRefused):
        LoopbackMtlsExchange(
            port=1234, expected_owner_dns="example.com", context=secure,
        )
